### ISSUE TITLE
'entr process dies when a watched file is deleted' still a question re-unresolved

### ISSUE THREAD

**Issue by toneboy** [clibs/entr#17]
The link in this solution is not longer valid: https://github.com/clibs/entr/issues/4

Does anyone know what the solution was? Thanks

**Comment by toneboy** [comment]
I was using an old version of entr 4.1-1. I think this issue was fixed in later versions.

**Comment by diasbruno** [comment]
Ah, ok...This repository is just a fork of [eradman/entr](https://github.com/eradman/entr).
So I think we must update this repo or GC it...

**Comment by diasbruno** [comment]
Since this is just because this repo is behind the original one, I've opened #18 to see what we can do.
