### ISSUE TITLE
ignores new directoried

### ISSUE THREAD

**Issue by GReagle** [clibs/entr#3]
entr, while in -d mode, doesn't exit when a new subdirectory is created or when the new subdirectory gets a new file.

By the way, great program.  Thanks.

**Comment by jwerle** [comment]
@GReagle  Please report issues to the original project repo [here](https://bitbucket.org/eradman/entr)
cc @eradman

**Comment by eradman** [comment]
Specifically you are encountering this issue:
https://bitbucket.org/eradman/entr/issues/27/not-working-on-a-vagrant-box-when-local

**Comment by GReagle** [comment]
@jwerle Thank you for the link to the original project repo.
@eradman I have no idea why you refer to issue 27.  My issue has nothing to do with a "Vagrant Box" (whatever that is), or NFS, or ssh, or any networking.

Anyway, I'll clone from the bitbucket original project repo and re-build and re-test.  If the problem still occurs I'll open an issue on bitbucket.

**Comment by jwerle** [comment]
FYI - I've updated this repo with the latest release from Eric.

**Comment by eradman** [comment]
@GReagle right, sorry I rashly assumed you were hitting yet anther instance of an inotify blind spot using stack mount points
